/** User statistics in Dead by Daylight */
export type UserStats = {
	DBD_KillerSkulls: number
	DBD_CamperSkulls: number
	DBD_KilledCampers: number
	DBD_SacrificedCampers: number
	DBD_TrapPickup: number
	DBD_ChainsawHit: number
	DBD_GeneratorPct_float: number
	DBD_HealPct_float: number
	DBD_EscapeKO: number
	DBD_Escape: number
	DBD_SkillCheckSuccess: number
	DBD_SacrificedCampers_iam: number
	DBD_KilledCampers_iam: number
	DBD_HookedAndEscape: number
	DBD_UnhookOrHeal: number
	DBD_UnhookOrHeal_PostExit: number
	DBD_BloodwebMaxLevel: number
	/** Bloodpoints earned */
	DBD_BloodwebPoints: number
	DBD_CamperMaxScoreByCategory: number
	DBD_SlasherMaxScoreByCategory: number
	DBD_BloodwebMaxPrestigeLevel: number
	DBD_UncloakAttack: number
	DBD_BloodwebPrestige3MaxLevel: number
	DBD_EscapeThroughHatch: number
	DBD_PerksCount_Idx0: number
	DBD_PerksCount_Idx1: number
	DBD_PerksCount_Idx2: number
	DBD_PerksCount_Idx3: number
	DBD_PerksCount_Idx268435456: number
	DBD_PerksCount_Idx268435457: number
	DBD_PerksCount_Idx268435458: number
	DBD_BloodwebPerkMaxLevel: number
	DBD_MaxBloodwebPointsOneCategory: number
	DBD_BurnOffering_UltraRare: number
	DBD_CamperFullLoadout: number
	DBD_SlasherFullLoadout: number
	DBD_CamperNewItem: number
	DBD_CamperKeepUltraRare: number
	DBD_AllEscapeThroughHatch: number
	DBD_CamperEscapeWithItemFrom: number
	DBD_UnlockRanking: number
	DBD_FinishWithPerks_Idx4: number
	DBD_EscapeNoBlood_MapAsy_Asylum: number
	DBD_FixSecondFloorGenerator_MapAsy_Asylum: number
	DBD_SlasherChainAttack: number
	DBD_SlasherChainInterruptAfter3: number
	DBD_FinishWithPerks_Idx268435459: number
	DBD_FinishWithPerks_Idx268435461: number
	DBD_FinishWithPerks_Idx5: number
	DBD_SlasherTierIncrement: number
	DBD_SlasherPowerKillAllCampers: number
	DBD_FixSecondFloorGenerator_MapSub_Street: number
	DBD_EscapeNoBlood_Obsession: number
	DBD_FinishWithPerks_Idx268435460: number
	DBD_DLC3_Slasher_Stat1: number
	DBD_DLC3_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx6: number
	DBD_FixSecondFloorGenerator_MapSwp_PaleRose: number
	DBD_DLC3_Camper_Stat1: number
	DBD_FinishWithPerks_Idx7: number
	DBD_HitNearHook: number
	DBD_LastSurvivorGeneratorEscape: number
	DBD_Camper8_Stat1: number
	DBD_Camper8_Stat2: number
	DBD_FinishWithPerks_Idx8: number
	DBD_DLC4_Slasher_Stat1: number
	DBD_DLC4_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435462: number
	DBD_Camper9_Stat2: number
	DBD_FinishWithPerks_Idx9: number
	DBD_DLC5_Slasher_Stat1: number
	DBD_DLC5_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435463: number
	DBD_FixSecondFloorGenerator_MapBrl_MaHouse: number
	DBD_FinishWithPerks_Idx268435464: number
	DBD_DLC6_Slasher_Stat2: number
	DBD_DLC6_Slasher_Stat1: number
	DBD_DLC7_Slasher_Stat1: number
	DBD_DLC7_Slasher_Stat2: number
	DBD_DLC7_Camper_Stat1: number
	DBD_DLC7_Camper_Stat2: number
	DBD_FinishWithPerks_Idx11: number
	DBD_FinishWithPerks_Idx268435465: number
	DBD_DLC8_Slasher_Stat1: number
	DBD_DLC8_Slasher_Stat2: number
	DBD_DLC8_Camper_Stat1: number
	DBD_Event1_Stat1: number
	DBD_Event1_Stat2: number
	DBD_Event1_Stat3: number
	DBD_FinishWithPerks_Idx12: number
	DBD_FinishWithPerks_Idx268435466: number
	DBD_FixSecondFloorGenerator_MapFin_Hideout: number
	DBD_DLC9_Slasher_Stat1: number
	DBD_DLC9_Slasher_Stat2: number
	DBD_DLC9_Camper_Stat1: number
	DBD_FixSecondFloorGenerator_MapAsy_Chapel: number
	DBD_FinishWithPerks_Idx10: number
	DBD_FinishWithPerks_Idx268435467: number
	DBD_Chapter9_Slasher_Stat1: number
	DBD_Chapter9_Slasher_Stat2: number
	DBD_Chapter9_Camper_Stat1: number
	DBD_FixSecondFloorGenerator_MapHti_Manor: number
	DBD_FinishWithPerks_Idx13: number
	DBD_FinishWithPerks_Idx268435468: number
	DBD_Chapter10_Slasher_Stat1: number
	DBD_Chapter10_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435469: number
	DBD_Chapter10_Camper_Stat1: number
	DBD_FixSecondFloorGenerator_MapKny_Cottage: number
	DBD_FinishWithPerks_Idx14: number
	DBD_Chapter11_Slasher_Stat1: number
	DBD_Chapter11_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435470: number
	DBD_Chapter11_Camper_Stat1_float: number
	DBD_FixSecondFloorGenerator_MapBrl_Temple: number
	DBD_FinishWithPerks_Idx15: number
	DBD_Chapter12_Slasher_Stat1: number
	DBD_Chapter12_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435471: number
	DBD_Chapter12_Camper_Stat1: number
	DBD_Chapter12_Camper_Stat2: number
	DBD_FinishWithPerks_Idx16: number
	DBD_Chapter13_Slasher_Stat1: number
	DBD_Chapter13_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435472: number
	DBD_FixSecondFloorGenerator_MapQat_Lab: number
	DBD_FinishWithPerks_Idx17: number
	DBD_FinishWithPerks_Idx18: number
	DBD_Chapter14_Slasher_Stat1: number
	DBD_Chapter14_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435473: number
	DBD_FixSecondFloorGenerator_MapHti_Shrine: number
	DBD_Chapter14_Camper_Stat1: number
	DBD_FinishWithPerks_Idx19: number
	DBD_Chapter15_Slasher_Stat1: number
	DBD_Chapter15_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435474: number
	DBD_FixSecondFloorGenerator_MapUkr_Saloon: number
	DBD_Chapter15_Camper_Stat1: number
	DBD_FinishWithPerks_Idx20: number
	DBD_Chapter16_Slasher_Stat1: number
	DBD_Chapter16_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435475: number
	DBD_FixSecondFloorGenerator_MapWal_Level_01: number
	DBD_Chapter16_Camper_Stat1_float: number
	DBD_FinishWithPerks_Idx21: number
	DBD_Chapter17_Slasher_Stat1: number
	DBD_Chapter17_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435476: number
	DBD_Chapter17_Camper_Stat1: number
	DBD_Chapter17_Camper_Stat2_float: number
	DBD_FinishWithPerks_Idx22: number
	DBD_Chapter18_Slasher_Stat1: number
	DBD_Chapter18_Slasher_Stat2: number
	DBD_Chapter18_Camper_Stat1: number
	DBD_Chapter18_Camper_Stat2_float: number
	DBD_FinishWithPerks_Idx23: number
	DBD_FinishWithPerks_Idx268435477: number
	DBD_Chapter19_Slasher_Stat1: number
	DBD_Chapter19_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435478: number
	DBD_Chapter19_Camper_Stat1: number
	DBD_Chapter19_Camper_Stat2: number
	DBD_FinishWithPerks_Idx24: number
	DBD_Chapter20_Slasher_Stat1: number
	DBD_Chapter20_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435479: number
	DBD_FixSecondFloorGenerator_MapEcl_Level_01: number
	DBD_FinishWithPerks_Idx26: number
	DBD_FinishWithPerks_Idx25: number
	DBD_Chapter21_Slasher_Stat1: number
	DBD_Chapter21_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435480: number
	DBD_Chapter21_Camper_Stat1: number
	DBD_Chapter21_Camper_Stat2: number
	DBD_FinishWithPerks_Idx27: number
	DBD_Chapter22_Slasher_Stat1: number
	DBD_Chapter22_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435481: number
	DBD_Chapter22_Camper_Stat1: number
	DBD_FixSecondFloorGenerator_MapIon_Level_01: number
	DBD_FinishWithPerks_Idx28: number
	DBD_Chapter23_Slasher_Stat1: number
	DBD_Chapter23_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435482: number
	DBD_Chapter23_Camper_Stat1: number
	DBD_Chapter23_Camper_Stat2: number
	DBD_FinishWithPerks_Idx29: number
	DBD_Chapter24_Slasher_Stat1: number
	DBD_Chapter24_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435483: number
	DBD_FixSecondFloorGenerator_MapMtr_Level_1: number
	DBD_Chapter24_Camper_Stat1: number
	DBD_FinishWithPerks_Idx30: number
	DBD_Chapter25_Slasher_Stat1: number
	DBD_Chapter25_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435484: number
	DBD_Chapter25_Camper_Stat1: number
	DBD_FinishWithPerks_Idx31: number
	DBD_FinishWithPerks_Idx32: number
	DBD_Chapter26_Slasher_Stat1: number
	DBD_Chapter26_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435485: number
	DBD_FixSecondFloorGenerator_MapQtm_Level_01: number
	DBD_Chapter26_Camper_Stat1: number
	DBD_FinishWithPerks_Idx33: number
	DBD_Chapter27_Slasher_Stat1: number
	DBD_Chapter27_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435486: number
	DBD_FixSecondFloorGenerator_MapInd_Forest: number
	DBD_FinishWithPerks_Idx34: number
	DBD_FinishWithPerks_Idx35: number
	DBD_Chapter28_Slasher_Stat1: number
	DBD_Chapter28_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435487: number
	DBD_FixSecondFloorGenerator_MapUba_Level_01: number
	DBD_Chapter28_Slasher_Stat3: number
	DBD_FinishWithPerks_Idx36: number
	DBD_Camper38_Stat1: number
	DBD_Camper38_Stat2: number
	DBD_FinishWithPerks_Idx37: number
	DBD_Chapter29_Slasher_Stat1: number
	DBD_Chapter29_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435488: number
	DBD_FixSecondFloorGenerator_MapWrm_Level_01: number
	DBD_Chapter29_Slasher_Stat3: number
	DBD_FinishWithPerks_Idx38: number
	DBD_Chapter30_Slasher_Stat1: number
	DBD_Chapter30_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435489: number
	DBD_Camper40_Stat1: number
	DBD_Camper40_Stat2: number
	DBD_FinishWithPerks_Idx39: number
	DBD_Chapter31_Slasher_Stat1: number
	DBD_Chapter31_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435490: number
	DBD_FixSecondFloorGeneratorMapApl_Level_01: number
	DBD_Chapter31_Camper_Stat1: number
	DBD_FinishWithPerks_Idx40: number
	DBD_Racoon_Dog_Triggered: number
	DBD_Chapter32_Slasher_Stat1: number
	DBD_Chapter32_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435491: number
	DBD_FixSecondFloorGenerator_MapQtm_Level_02: number
	DBD_Chapter32_Camper_Stat1: number
	DBD_FinishWithPerks_Idx41: number
	DBD_Camper43_Stat1: number
	DBD_Camper43_Stat2: number
	DBD_FinishWithPerks_Idx42: number
	DBD_Chapter33_Slasher_Stat1: number
	DBD_Chapter33_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435492: number
	DBD_Chapter33_Camper_Stat1: number
	DBD_Chapter33_Camper_Stat2: number
	DBD_FinishWithPerks_Idx43: number
	DBD_Chapter34_Slasher_Stat1: number
	DBD_Chapter34_Slasher_Stat2: number
	DBD_FinishWithPerks_Idx268435493: number
	DBD_Chapter34_Camper_Stat1: number
	DBD_Chapter34_Camper_Stat2: number
	DBD_FinishWithPerks_Idx44: number
}
